# ai_note_generator_worker.py
#
# Worker class that generates Zettelkasten-style notes from PDF content or raw text
# using Google Gemini AI, and atomically commits notes and links to SQLite.
# Executed in a background thread to prevent UI freezing.

import os
import threading
import traceback
from uuid import uuid4
from datetime import datetime
from typing import Optional, Callable, List, Dict, Any

from gemini_api_client import GeminiApiClient, GeminiApiError, GeminiAuthError, GeminiRateLimitError
import note_service
import database_manager
import pdf_processor
from logger import log_debug, log_error


class AiNoteGeneratorWorker:
    """
    Worker that executes the AI note generation and database persistence in a background thread.
    Supports cancellation and atomic batch rollback.
    """
    def __init__(
        self,
        extracted_text: str,
        on_finished: Optional[Callable[[List[Dict[str, Any]]], None]] = None,
        on_error: Optional[Callable[[str], None]] = None
    ):
        self.extracted_text = extracted_text
        self.extracted_text_or_path = extracted_text
        self.on_finished = on_finished
        self.on_error = on_error
        self._cancel_event = threading.Event()

    def cancel(self) -> None:
        """Signals the worker to cancel the ongoing generation process."""
        self._cancel_event.set()

    def is_cancelled(self) -> bool:
        """Returns True if the worker process has been cancelled."""
        return self._cancel_event.is_set()

    def run(self) -> None:
        """Main execution method for the background worker thread."""
        db_manager_worker = None
        try:
            # Check for early cancellation
            if self._cancel_event.is_set():
                log_debug("DEBUG: AiNoteGeneratorWorker cancelled before start.")
                return

            # 1. Resolve text content (extract from PDF if path provided, or use raw text)
            if isinstance(self.extracted_text_or_path, str) and (
                self.extracted_text_or_path.lower().endswith(".pdf") or os.path.isfile(self.extracted_text_or_path)
            ):
                text_content = pdf_processor.extract_text_from_pdf(self.extracted_text_or_path)
            else:
                text_content = self.extracted_text_or_path

            if not text_content or not str(text_content).strip():
                raise ValueError("Input text is empty or contains no readable content.")

            # Check for cancellation before expensive API calls
            if self._cancel_event.is_set():
                log_debug("DEBUG: AiNoteGeneratorWorker cancelled before Gemini API call.")
                return

            # 2. Initialize thread-local DatabaseManager
            db_manager_worker = database_manager.DatabaseManager(init_tables=False)

            # 3. Initialize Gemini API Client and generate notes
            gemini_client = GeminiApiClient()
            generated_notes = gemini_client.generate_zettelkasten_notes(text_content)

            # Check for cancellation after API call
            if self._cancel_event.is_set():
                log_debug("DEBUG: AiNoteGeneratorWorker cancelled after Gemini API call.")
                return

            if not generated_notes:
                log_debug("DEBUG: No notes generated by Gemini API.")
                if self.on_finished:
                    try:
                        self.on_finished([])
                    except Exception as cb_err:
                        log_error(f"Error in on_finished callback: {cb_err}")
                return

            # 4. Stage 1: Build fresh mapping of existing notes & disambiguate titles
            title_to_id = db_manager_worker.get_all_note_titles_and_ids()
            used_titles = set(title_to_id.keys())
            batch_title_to_id = {}
            log_debug(f"DEBUG: Initial title_to_id count: {len(title_to_id)}")

            for note_data in generated_notes:
                if not isinstance(note_data, dict):
                    continue

                raw_title = note_data.get('title', 'Untitled Note')
                sanitized_title = note_service.sanitize_title(f"# {raw_title}")
                final_title = note_service.disambiguate_title(sanitized_title, used_titles)

                used_titles.add(final_title)
                new_id = str(uuid4())

                note_data['_final_id'] = new_id
                note_data['_final_title'] = final_title
                note_data['_is_new'] = True

                batch_title_to_id[final_title] = new_id
                batch_title_to_id[sanitized_title] = new_id
                batch_title_to_id[raw_title] = new_id

                title_to_id[final_title] = new_id
                if sanitized_title not in title_to_id:
                    title_to_id[sanitized_title] = new_id
                if raw_title not in title_to_id:
                    title_to_id[raw_title] = new_id

            # 5. Stage 2: Prepare batch insertion records and connections
            notes_to_insert = []
            links_to_insert = []
            now = datetime.now().isoformat()

            for note_data in generated_notes:
                if not isinstance(note_data, dict):
                    continue

                final_id = note_data['_final_id']
                final_title = note_data.get('_final_title', note_data.get('title', 'Untitled Note'))
                content = note_data.get('content', '')
                category = note_data.get('general_title', 'AI Generated')

                full_content = f"# {final_title}\n\n{content}"

                notes_to_insert.append(
                    (final_id, final_title, full_content, category, now, now)
                )

                connections = note_data.get('connections', [])
                if isinstance(connections, list):
                    for target_title_raw in connections:
                        if not isinstance(target_title_raw, str):
                            continue
                        sanitized_target_title = note_service.sanitize_title(target_title_raw)
                        target_id = (
                            batch_title_to_id.get(sanitized_target_title)
                            or batch_title_to_id.get(target_title_raw)
                            or title_to_id.get(sanitized_target_title)
                            or title_to_id.get(target_title_raw)
                        )
                        # Avoid self-referential links and ensure target exists
                        if target_id and target_id != final_id:
                            link_pair = (final_id, target_id)
                            if link_pair not in links_to_insert:
                                links_to_insert.append(link_pair)
                        elif not target_id:
                            log_debug(f"DEBUG: Could not find target_id for '{target_title_raw}'. Link not inserted.")

            # Check for cancellation before DB commit
            if self._cancel_event.is_set():
                log_debug("DEBUG: AiNoteGeneratorWorker cancelled before database commit.")
                return

            # 6. Stage 3: Atomic single-transaction database insertion
            try:
                db_manager_worker.bulk_insert_notes_and_links(notes_to_insert, links_to_insert)
                log_debug(f"DEBUG: Atomically inserted {len(notes_to_insert)} notes and {len(links_to_insert)} links.")
            except Exception as db_err:
                log_error(f"Database error during atomic batch insertion: {db_err}")
                raise db_err

            # 7. Safe callback dispatch
            if self.on_finished:
                try:
                    self.on_finished(generated_notes)
                except Exception as cb_err:
                    log_error(f"Error in on_finished callback: {cb_err}\n{traceback.format_exc()}")

        except (GeminiAuthError, GeminiRateLimitError, GeminiApiError) as ge:
            err_msg = str(ge)
            log_error(f"AiNoteGeneratorWorker Gemini API error: {err_msg}")
            if self.on_error:
                try:
                    self.on_error(err_msg)
                except Exception as cb_err:
                    log_error(f"Error in on_error callback: {cb_err}")
        except (ValueError, FileNotFoundError) as ve:
            err_msg = str(ve)
            log_error(f"AiNoteGeneratorWorker validation error: {err_msg}")
            if self.on_error:
                try:
                    self.on_error(err_msg)
                except Exception as cb_err:
                    log_error(f"Error in on_error callback: {cb_err}")
        except Exception as e:
            err_msg = f"An error occurred during AI note generation: {e}"
            log_error(f"AiNoteGeneratorWorker unhandled exception: {err_msg}\n{traceback.format_exc()}")
            if self.on_error:
                try:
                    self.on_error(err_msg)
                except Exception as cb_err:
                    log_error(f"Error in on_error callback: {cb_err}")
        finally:
            if db_manager_worker:
                try:
                    db_manager_worker.close_connection()
                except Exception as close_err:
                    log_error(f"Error closing DB connection: {close_err}")
