# models.py
#
# Domain entities and value objects for Zettelkasten AI Notes.

from dataclasses import dataclass, field
from typing import List, Optional
from datetime import datetime


@dataclass
class NoteMetadata:
    """Lightweight metadata representation of a note for lists and lookups."""
    id: str
    title: str
    category: str = ""

    def to_tuple(self) -> tuple[str, str, str]:
        return (self.id, self.title, self.category)


@dataclass
class Note:
    """Full domain model for a Zettelkasten note."""
    id: str
    title: str
    content: str
    category: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())

    @property
    def metadata(self) -> NoteMetadata:
        return NoteMetadata(id=self.id, title=self.title, category=self.category)

    def to_db_tuple(self) -> tuple[str, str, str, str, str, str]:
        return (self.id, self.title, self.content, self.category, self.created_at, self.updated_at)


@dataclass
class NoteLink:
    """Represents a directional or bidirectional connection between two notes."""
    source_note_id: str
    target_note_id: str

    def to_tuple(self) -> tuple[str, str]:
        return (self.source_note_id, self.target_note_id)


@dataclass
class GeneratedAiNote:
    """Represents a note generated by the Gemini AI client."""
    title: str
    content: str
    general_title: str = "AI Generated"
    connections: List[str] = field(default_factory=list)
    final_id: Optional[str] = None
    final_title: Optional[str] = None


@dataclass
class DocumentStats:
    """Text and reading statistics for note content."""
    words: int = 0
    chars: int = 0
    lines: int = 0
    reading_time_min: int = 0

    def __getitem__(self, key: str):
        return getattr(self, key)

    def to_dict(self) -> dict:
        return {
            "words": self.words,
            "chars": self.chars,
            "lines": self.lines,
            "reading_time_min": self.reading_time_min,
        }

